import os

GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET')
SECRET_KEY = os.getenv('SECRET_KEY')
AUDIENCE = os.getenv('AUDIENCE')
DATA_LAYER_URL = os.getenv('DATA_LAYER_URL')
PROJECT_ID = os.getenv('PROJECT_ID')